# fly.toml app configuration file generated for f3-xicons-2 on 2025-05-30T16:49:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'f3-xicons-2'
primary_region = 'sjc'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
